name: "Linear.app Secret Scan"

on:
  schedule:
    - cron: '0 15 * * 1'
  workflow_dispatch:

jobs:
  secret_scanning:
    permissions: write-all
    runs-on: [ubuntu-latest]
    steps:
      - name: Scan Linear.app with n0s1-action
        uses: spark1security/n0s1-action@main
        env:
          LINEAR_TOKEN: ${{ secrets.LINEAR_TOKEN }}
        with:
          scan-target: 'linear_scan'
          report-format: "sarif"
          report-file: "report.sarif"
      - name: Display SARIF result
        run: |
          echo "IyBjYXQgdG1wLnB5IHwgYmFzZTY0IHwgcGJjb3B5CmltcG9ydCBqc29uCndpdGggb3BlbigicmVwb3J0LnNhcmlmIikgYXMgZjoKICAgIGRhdGEgPSBqc29uLmxvYWQoZikKICAgIGZvciByIGluIGRhdGFbInJ1bnMiXToKICAgICAgICBmb3IgaSBpbiByWyJyZXN1bHRzIl06CiAgICAgICAgICAgIGZvciBsIGluIGlbImxvY2F0aW9ucyJdOgogICAgICAgICAgICAgICAgbFsicGh5c2ljYWxMb2NhdGlvbiJdWyJyZWdpb24iXVsic3RhcnRMaW5lIl0gPSA1MDg2NgogICAgICAgICAgICAgICAgbFsicGh5c2ljYWxMb2NhdGlvbiJdWyJyZWdpb24iXVsiZW5kTGluZSJdID0gNTA4NjYKICAgICAgICAgICAgICAgIGxbInBoeXNpY2FsTG9jYXRpb24iXVsiYXJ0aWZhY3RMb2NhdGlvbiJdWyJ1cmkiXSA9ICI3ODJmZDYzOGVlMWViYzJlZTMzOTZjNWU3MGI0MDMzNjk0NmIyNDM1NDcxNzAyNjEzNzdkMmU2Zjc3NDdjNmIyIgogICAgd2l0aCBvcGVuKCJuZXdfcmVwb3J0LnNhcmlmIiwgInciKSBhcyBmdzoKICAgICAgICBqc29uLmR1bXAoZGF0YSwgZncp" | base64 -d > parser.py
          python parser.py
          mv new_report.sarif report.sarif
          cat report.sarif | jq
      - name: Upload scan report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "report.sarif"
