name: "Slack Secret Scan"

on:
  schedule:
    - cron: '0 16 * * 1'
  workflow_dispatch:

jobs:
  secret_scanning:
    permissions: write-all
    runs-on: [ubuntu-latest]
    steps:
      - name: Scan Slack with n0s1-action
        uses: spark1security/n0s1-action@main
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          scan-target: 'slack_scan'
          report-format: "sarif"
          report-file: "report.sarif"
      - name: Display SARIF result
        run: |
          cat report.sarif | jq | head -n 20
          cat report.sarif | jq | tail -n 20
      - name: Upload scan report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "report.sarif"
